#!/bin/sh -

OS=`uname`

ENABLE_VIDEO=yes
ENABLE_SPEEX=yes
ENABLE_GSM=yes
#ENABLE_ILBC=no

AMSIP_PREFIX=/usr/local/antisip

SRTP_OPTIONS=""
SRTP_CPPFLAGS=""
SRTP_CFLAGS="-fPIC -DPIC"
SRTP_LIBS=""

ORTP_OPTIONS="--with-srtp=$AMSIP_PREFIX"
ORTP_CPPFLAGS=""
ORTP_CFLAGS=""
ORTP_LIBS=""

LIBSPEEX_OPTIONS="--enable-sse"
LIBSPEEX_CPPFLAGS=""
LIBSPEEX_CFLAGS=""
LIBSPEEX_LIBS=""

LIBGSM_OPTIONS=""
#NOT USABLE LIBGSM_CFLAGS=""
#NOT USABLE LIBGSM_LIBS=""

LIBILBC_OPTIONS=""
LIBILBC_CPPFLAGS=""
LIBILBC_CFLAGS=""
LIBILBC_LIBS=""

MSVIDEOSTITCHERPLUGIN_OPTIONS="PKG_CONFIG_PATH="$AMSIP_PREFIX/lib/pkgconfig/""
MSVIDEOSTITCHERPLUGIN_CPPFLAGS="-I$AMSIP_PREFIX/include"
MSVIDEOSTITCHERPLUGIN_CFLAGS=""
MSVIDEOSTITCHERPLUGIN_LIBS="-L$AMSIP_PREFIX/lib -lavutil"

LIBTHEORA_OPTIONS="--disable-oggtest --disable-vorbistest --disable-sdltest"
LIBTHEORA_CPPFLAGS="-I$AMSIP_PREFIX/include"
LIBTHEORA_CFLAGS=""
LIBTHEORA_LIBS="-L$AMSIP_PREFIX/lib"

LIBFFMPEG_OPTIONS="--enable-shared"

LIBMEDIASTREAMER2_OPTIONS="PKG_CONFIG_PATH=$AMSIP_PREFIX/lib/pkgconfig/ --disable-video --disable-strict -with-gsm=$AMSIP_PREFIX"
LIBMEDIASTREAMER2_CPPFLAGS="-I$AMSIP_PREFIX/include -DAMD_HACK"
LIBMEDIASTREAMER2_CFLAGS=""
LIBMEDIASTREAMER2_LIBS="-L$AMSIP_PREFIX/lib"
if test "x$ENABLE_VIDEO" = xyes; then
 LIBMEDIASTREAMER2_OPTIONS="PKG_CONFIG_PATH=$AMSIP_PREFIX/lib/pkgconfig/ --disable-strict -with-gsm=$AMSIP_PREFIX --disable-libv4l"
 LIBMEDIASTREAMER2_CPPFLAGS="-I$AMSIP_PREFIX/include -DAMD_HACK"
 LIBMEDIASTREAMER2_CFLAGS=""
 LIBMEDIASTREAMER2_LIBS="-L$AMSIP_PREFIX/lib"
fi

LIBOSIP_OPTIONS=""
LIBOSIP_CPPFLAGS=""
LIBOSIP_CFLAGS=""
LIBOSIP_LIBS=""

LIBEXOSIP_OPTIONS=""
LIBEXOSIP_CPPFLAGS=""
LIBEXOSIP_CFLAGS=""
LIBEXOSIP_LIBS=""

LIBAMSIP_OPTIONS=""
LIBAMSIP_CPPFLAGS="-I$AMSIP_PREFIX/include"
LIBAMSIP_CFLAGS=""
LIBAMSIP_LIBS=""

if test "x$ENABLE_VIDEO" = xyes; then
 LIBAMSIP_OPTIONS="--enable-video"
 LIBAMSIP_CPPFLAGS="-I$AMSIP_PREFIX/include"
 LIBAMSIP_CFLAGS=""
 LIBAMSIP_LIBS="-L$AMSIP_PREFIX/lib"
fi



